inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: '2.7'

Layout/DotPosition:
  EnforcedStyle: 'trailing'

Lint/RescueException:
  Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - 'bin/foreman-node'

Style/HashSyntax:
  EnforcedStyle: hash_rockets
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/SignalException:
  EnforcedStyle: only_raise

Style/SymbolArray:
  EnforcedStyle: brackets

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'smart_proxy_salt.gemspec'